### ISSUE TITLE
Mobile menu pushing content in Safari

### ISSUE THREAD

**Issue by thetwopct** [saltnpixels/ignition#1]
Spotted an issue with the mobile navigation in Safari, it moves the whole site across instead of over the top

![new site just another wordpress site 2019-01-04 17-22-50](https://user-images.githubusercontent.com/10615884/50681791-b2cccf00-1047-11e9-94c3-939cb3142a0b.jpg)

**Comment by saltnpixels** [comment]
Yes this is how the site works until you hit the mobile media query. You can change this behavior under variables.scss
Look for $panel-left-absolute.

**Comment by thetwopct** [comment]
Ah OK understand :)
