### ISSUE TITLE
localhost times out

### ISSUE THREAD

**Issue by mmoga** [saltnpixels/ignition#13]
Hello! Sorry for the frank title of this issue. 😐 I've just started to try out Ignition, but when running `npm start` a https://localhost:3000 window opens up and then stalls out with the message "localhost didn’t send any data.
ERR_EMPTY_RESPONSE." 

I see that Browsersync is running as expected on port : 3001, so I'm not sure where the issue lies:
```
[Browsersync] Proxying: http://flps.local
[Browsersync] Access URLs:
 ------------------------------------
       Local: https://localhost:3000
    External: https://flps.local:3000
 ------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ------------------------------------
[Browsersync] Watching files...
```
Let me know what information I should provide and I'll post it.

Thank you~~

**Comment by saltnpixels** [comment]
Interesting... 
are you running a local server for the WordPress site?
I’ve never gotten this error before...

**Comment by mmoga** [comment]
@saltnpixels Oop—my Flywheel local setup was wrong. Sorry for the waste of time.

**Comment by mmoga** [comment]
Actually, now I'm getting `ERR_TOO_MANY_REDIRECTS` at localhost:3000 after adding my existing WP site to Flywheel Local. I'm a beginner at both this and Local, so perhaps I am missing something. The `site.local` address is working as expected, however, for Local. 

Do you (@saltnpixels or anyone else) have any tips or resources y'all could share? 🙏

**Comment by saltnpixels** [comment]
I would need more info to understand why you are getting these errors.
Name of local site made in local
show me your theme.config file also.

**Comment by mmoga** [comment]
@saltnpixels, thank you for looking into this. The site on local is `flps.local`.

And this is the theme.config:
```javascript
{
  "name": "FLPS Theme",
  "slug": "flps-theme",
  "local": "flps.local",
  "google_fonts": ["Roboto:400,400i,700,700i", "Roboto Slab:400,700"],
  "menu_icon": "",
  "sidebar_icon": "",
  "submenu_arrow_icon": "",
  "comment_icon": "",
  "search_menu_item": false,
  "dev_admin_bar_color": "#156288",
  "admin_access_capability": "manage_options",
  "load_custom_icons": false,
  "mobile_menu_type": "app-menu",
  "logo-position": "logo-left",
  "site-top-container": "container",
  "default-acf-header-block": ["post", "page"]
}
