### ISSUE TITLE
best way to have an ignition version of front-page.php?

### ISSUE THREAD

**Issue by mrskeety** [saltnpixels/ignition#14]
One thing that isn't immediately clear to me from the docs is how to achieve a completely different home page where a page is specified as a static home page.

Usually, I'd have a front-page.php template. But that doesn't seem like it is the Ignition way of doing things? I'd guessed at using the parts approach but that seems to work only with post types?

Is there an easy way of doing this or do I just use a front-page.php file, like I normally would and create that from a copy of page.php?

**Comment by saltnpixels** [comment]
Why do you need a front-page.php?
you can create blocks and stitch them together in a regular page and make that your home page. That's how I do it. If I am really lazy I make one big block that holds like 3 sections for the front page... :D 

Or you can simply copy page.php and start making a homepage with that.
