### ISSUE TITLE
Skipping terminal and installing directly through the Themes "Add New" button?

### ISSUE THREAD

**Issue by paaljoachim** [saltnpixels/ignition#19]
Hey

I happen to not use terminal first and went straight to installing the theme. It seems that all styles were stripped.
What about having a way to just installing the theme through the "Add New" button in the themes panel?

Btw
I am checking to also see that the theme is updated on occasion.

**Comment by saltnpixels** [comment]
The theme involves knowledge on using npm. 
you need to run this to build the theme and install it. 

it creates a dist folder which has the theme styles

**Comment by paaljoachim** [comment]
Alrighty!

**Comment by paaljoachim** [comment]
Alrighty!
