### ISSUE TITLE
Gutenberg insert image "full width" not 100% width

### ISSUE THREAD

**Issue by thetwopct** [saltnpixels/ignition#2]
I've noticed that when inserting an image via Gutenberg and then selecting its alignment as "full width" the image doesn't stretch all the way across the page:

![new site just another wordpress site 2019-01-04 18-14-38](https://user-images.githubusercontent.com/10615884/50683432-01c93300-104d-11e9-948f-5354a5dfd3e1.jpg)

I've been trying to work out why, seems to be something to do with max-width of the wp-block-image

`.wp-block-image {
max-width: 100%;
}`

**Comment by saltnpixels** [comment]
Gutenberg keeps updating and changing things. They add css sometimes that messes things up!
I have made a fix for this as well as some other fixes.
Thanks for reporting this!!
