### ISSUE TITLE
Ignition expects you to have ACF Pro installed so you can utilize all of its goodness. So go buy and install ACF Pro!

### ISSUE THREAD

**Issue by LukaszJaro** [saltnpixels/ignition#23]
What happens/breaks if you don't have ACF pro?

**Comment by saltnpixels** [comment]
You wont have access to all the ACF goodness!

It should still work. you wont have the theme settings page and its options. And you wont have the ability to make the header blocks which come with ignition.

Let me know if you run into any problems.

**Comment by LukaszJaro** [comment]
Thanks for the quick reply!

Interesting theme with lots going on!
