### ISSUE TITLE
Logo not centered in logo-in-middle position/display bug

### ISSUE THREAD

**Issue by ThatKDB** [saltnpixels/ignition#3]
When selecting logo-in-middle option the logo is not centered on the page. I had 3 top level menu items, which means the extra item to the left pushes the logo off center. When I add another top level menu item, the logo no longer displays until removing the new item and selecting another logo position.

**Comment by saltnpixels** [comment]
Unfortunately I cannot find a way to refresh the logo position in the customizer when you add/remove menu items. 
I cannot find a callback or function for the wp customizer when it comes to adding a menu item. There isn't really any documentation on the javascript side of the wp menu that I can find. :( 

The good news is it won't affect the site when it is live, it's only in the customizer. Until I figure out a fix, just make sure to add your menu items first then change the logo location.

**Comment by ThatKDB** [comment]
Understandable. I was also having the display issue on the live site after publishing the change. The logo seems to have a display:none applied. I'll give your suggestion a try to see if it is a viable workaround for me. 

BTW, thanks for a great starter theme. I'm giving it a spin for a new project, which will be my first custom theme ;)

**Comment by saltnpixels** [comment]
I just released version 2 which fixed and added a lot of stuff.
I will look into the logo in the middle later today and see if there are any issues I may have missed.
I appreciate all the feedback and bug finds!

Eric Greenfield

**Comment by ThatKDB** [comment]
Awesome! I just generated a new download and have copied it over to my project. Thanks for the goodies!

**Comment by saltnpixels** [comment]
I made an adjustment so certain plugins will work better with ignition so you may want to download again. :) (plugins like bbpress or big plugins like that...)

Some plugins use page.php to show all their stuff even if it's an archive or a post type. This didn't sit well with ignition which routes your pages based on is_page(). So That has been fixed.

**Comment by ThatKDB** [comment]
I tried your suggested workaround -- doesn't quite work at the moment. It ends up putting the site logo in the sub menu of the menu item to the right of where the logo should be. I'll try to see if I can play with it so more next week.

**Comment by saltnpixels** [comment]
It seems to be working for me. I guess I would need some more information

**Comment by ThatKDB** [comment]
I tested on the dev environment from my webhost and I don't get any of these issues there. Must be related to the Local by Flywheel local environment. My hosted dev install doesn't experience the disappearing logo in customizer either. I wasn't able to see anything in the console. I tried in multiple browsers and using private windows with similar results. Must be some weird issue from LbF.
