### ISSUE TITLE
Source map not being output correctly

### ISSUE THREAD

**Issue by ThatKDB** [saltnpixels/ignition#4]
CSS sourcemaps aren't being output correctly. Chrome only reports main.css from the css sourcemap (ommiting all the .scss files) and no JS sourcemap. I'm not sure if this is a Ignition-specific issue or something to do with WP-Gulp.

**Comment by saltnpixels** [comment]
I think its a mixture of both. 
WP Gulp has the gulp sourcemaps set to not include the content, but then it does not state where the source files are. Perhaps WP Gulp assumes your source files are in the root. Ignition has them in assets/sass.
I fixed this and it should work now.
Thanks for pointing it out!

**Comment by ThatKDB** [comment]
Awesome! I'm glad it was a quick fix!
