### ISSUE TITLE
Error in Mixin

### ISSUE THREAD

**Issue by cinghaman** [saltnpixels/ignition#6]
When Compiling sass It throws error here 
`Running "sass:dist" (sass) task
Error: Invalid CSS after "  @if($sizeValue ": expected ")", was "= 16){"
        on line 6 of assets/sass/site/_mixin.scss
`
Changing to  @if($sizeValue : 16) fixes it

I am using grunt btw if that makes a difference

**Comment by saltnpixels** [comment]
It seems to work for me, but I am using gulp.
Anyways I would think it should be == 16. I can make that change.

Why dont you run gulp? use npm start on the project after npm install.

**Comment by cinghaman** [comment]
I do NPM but I just have most of my project setup with grunt, due to the way our system is at work

**Comment by saltnpixels** [comment]
Anyways i fixed it, so you can redownload and let me know if it works better

**Comment by cinghaman** [comment]
Yup Works

**Comment by saltnpixels** [comment]
Thanks for submitting the bug :)
