### ISSUE TITLE
Questions || Ignition deployment

### ISSUE THREAD

**Issue by quintendewilde** [saltnpixels/ignition#8]
As I don't find a contact or question of FAQ on the website. I'm going to ask my questions here. 

I find the gap in knowing basic coding for web and the jump it makes to deploying or managing WordPress based systems is a big jump.

Is it possible to host ignition on a shared hosting where there is no possibility to enter a command line or install node.js. 

What kind of hosting should I have when I'm unable to do the former. 

And is this platform thus made for making websites for simple portfolio's. 

To you, they must look like obvious simple questions. But to me they would be a great help in finding the correct tool and or host in the maze of a zillion possibilities.

**Comment by saltnpixels** [comment]
I am so sorry that I somehow missed this.

 - node js needs to run locally not on the hosting server. You create the theme locally and then put it on the shared hosting environment.
- any hosting that works with WordPress will work
- ignition is a theme you can use to build anything provided you know how to code. so you can make a portfolio if you know php, JS, and html
